### ISSUE TITLE
Should include read me with instruction on use

### ISSUE THREAD

**Issue by slapsruler12** [3249V/Gimkit-Bot#1]
Selenium is not found when running python script. I assume it just has to be downloaded, however there is no instruction on that.

**Comment by 3249V** [comment]
I'm working on that. The goal is to have an executable file to run this, though that is still in progress. Thanks for checking my project out though!

**Comment by Mippy** [comment]
use pip stupid stupid head stupid head

**Comment by isabelcoolaf** [comment]
`python -m pip install selenium`
`python Tkinter.py`

you'll want to do these in the command prompt
