### ISSUE TITLE
Broken driver.find_element_by

### ISSUE THREAD

**Issue by polarbub** [3249V/Gimkit-Bot#4]
On lines 131, 137, and 139 of main.py the xpath is invalid. it should be replaced by
`attacker = self.driver.find_element_by_class_name("sc-dchYKM")`
on line 131,
`menu = self.driver.find_element_by_class_name("MuiButtonBase-root")` 
on line 137, and
`back = self.driver.find_element_by_class_name("MuiBackdrop-root")`
on line 139.
With those fixes it doesn't do anything once it is in game. I suspect it has something to do with find_element_by_xpaths that should be replaced by find_element_by_classe_names.

**Comment by Geekknight777** [comment]
how do u even get it to work. Im new to python

**Comment by polarbub** [comment]
Um, it doesn't work, it would be quite a bit of work to fix it. You need to find the new xpaths for all the elements and put them in the code. GimKit changes these often so it's an uphill battle to keep repos like these maintained.
